### ISSUE TITLE
Potential segmentation fault on High Sierra (10.13.4)

### ISSUE THREAD

**Issue by hmm-norah** [mttrb/antipopd#2]
Hey! This is my first issue post in a long time, so I apologize if I'm leaving anything out that is glaringly obvious. I will be happy to amend this issue with necessary information.

The issue that I'm seeing is that after building with the given instructions, the program gives a segmentation fault code related to bad access.

The computer I am using this on is a PC running Mac OS, and so if this runs on High Sierra on real Macs, then there is clearly not a real issue here. The world of debugging unofficial Mac issues is surely a nightmare, and no one could be blamed for not wanting to investigate further.

Included is a terminal log where I:
* Build with debugging symbols
* Open antipopd in lldb
* Set a breakpoint at the exact line that causes the crash
* Print the value being passed into the function 'CFGetTypeID( )'
* Take one step in lldb, which displays the crash
* Exit lldb. Run antipopd as a normal user, and as root, which both result in a segmentation fault

Thank you for reading this issue, take care

```

div@mac [antipopd]: clang -g -framework CoreFoundation -framework Foundation -framework SystemConfiguration -framework AppKit -arch i386 -arch x86_64 -o antipopd antipopd.m
div@mac [antipopd]: lldb antipopd
(lldb) target create "antipopd"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'antipopd' (x86_64).
(lldb) b antipopd.m:78
Breakpoint 1: where = antipopd`getPowerStatus + 43 at antipopd.m:78, address = 0x000000010000165b
(lldb) r
Process 62898 launched: '/Users/div/code/antipopd/antipopd' (x86_64)
Process 62898 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x000000010000165b antipopd`getPowerStatus(store=0x00000001001050c0, changedKeys=@"1 element", info=0x0000000000000000) at antipopd.m:78
   75  		);
   76
   77  		// We should always get a dictionary but we'll check anyway
-> 78  		if (CFGetTypeID(value) == CFDictionaryGetTypeID()) {
   79
   80  			//Get the Power Source State
   81  			CFStringRef powerSourceState = CFDictionaryGetValue(value, POWER_SOURCE);
Target 0: (antipopd) stopped.
(lldb) print value
(CFPropertyListRef) $0 = 0x0000000000000000
(lldb) s
Process 62898 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x00007fff55ba70ca CoreFoundation`CFGetTypeID + 10
CoreFoundation`CFGetTypeID:
->  0x7fff55ba70ca <+10>: movq   0x8(%rdi), %rcx
    0x7fff55ba70ce <+14>: movq   (%rdi), %rax
    0x7fff55ba70d1 <+17>: testq  %rax, %rax
    0x7fff55ba70d4 <+20>: je     0x7fff55ba70f9            ; <+57>
Target 0: (antipopd) stopped.
(lldb) exit
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
div@mac [antipopd]: ./antipopd
Segmentation fault: 11
div@mac [antipopd]: sudo ./antipopd
Password:
Segmentation fault: 11

```

**Comment by driph** [comment]
Seeing the same results here, on 10.13.6.

**Comment by mttrb** [comment]
I've finally had some time to look at this and I've rewritten `antipopd` to compile and run on more modern macOS versions.
